### PR TITLE
quick and dirty 1.20 port

### PR DESCRIPTION
**Pull request by petersv5**
A very mechanical port to 1.20 based on suggestions from the Fabric team here https://fabricmc.net/2023/05/25/120.html. We did it to allow us to start testing for a server update to 1.20. Feel free to use it any way you want.

Mainly it is updating calls to sendFeedback() to pass a Supplier<Text> instead of a Text parameter.

The changes to handle the removal of Material are not fully tested. The isSolid() call is marked as deprecated, so that should probably be something else.

### CODE REVIEW

**Comment by John-Paul-R** [comment]
This is great, thanks a bunch! I'll look at getting this merged later today! (Also, thanks for the callouts in the PR desc) 
_([msg copied from discord](https://discord.com/channels/513219024927326211/857077956336943154/1115984133525610506))_

**Comment by petersv5** [comment]
Note that this commit was for 1.20-rc1.

I think I also forgot to bump the version number for the Placeholder-API. When I try to do that I get a compilation error in some of the tests though.

**Comment by John-Paul-R** [comment]
Looks like a good start. Thanks a bunch!

**Comment by John-Paul-R** [comment]
> Note that this commit was for 1.20-rc1.
> 
> I think I also forgot to bump the version number for the Placeholder-API. When I try to do that I get a compilation error in some of the tests though.

I'll address these as I work towards a full 1.20 release. Ty for the heads-up

**Pull request merged**
