### PR TITLE
Update to 1.20.5

### PR DESCRIPTION
**Pull request by arnokeesman**
untested, runServer task still/again broken
did the wrapper in a seperate commit, turns out binaries are a security risk

### CODE REVIEW

**Comment by John-Paul-R** [comment]
@arnokeesman Thanks for putting this together! You OK with this being published and I give review, or should I merge this and make any necessary changes on top of that? (or something else?)

**Comment by arnokeesman** [comment]
whatever works best for you

**Comment by arnokeesman** [comment]
Also, there are comments and thoughts in some commit messages
Something there might be actionable

**Comment by John-Paul-R** [comment]
Sounds good. I agree with the decisions made. Will update that config option name soon.

Thanks again!

**Pull request merged**
