### PR TITLE
Attempt at porting over the `excluded_top_level_commands` setting to 1.18.2

### PR DESCRIPTION
**Pull request by elpocoburrito**
Haven't tested if the changes work, or even build, as it asks for an API key to build.

Hopefully the github action will build this PR so i can test it.

### CODE REVIEW

**Comment by elpocoburrito** [comment]
Okay it's building on my fork, will update once i test the artifact

**Comment by John-Paul-R** [comment]
Will copy over these changes to the `1.18` branch as well (which is actually the `1.18.2` branch because... reasons..) Thanks for doing this!

**Comment by John-Paul-R** [comment]
(Assuming you actually want this backported to 1.18.1) For this changeset, you'll want to add a call to `.getValue()` on the `CONFIG` properties on lines 59 & 60 of `EssentialCommandRegistry.java`

**Comment by John-Paul-R** [comment]
#176 and #177 backported all modern EC features to the 1.18.x and 1.17.x branches respectively, so this is complete.

**Pull request closed without merging**
