### PR TITLE
backport to 1.20.1

### PR DESCRIPTION
**Pull request by arnokeesman**
this one's gonna need a separate branch, too many people still on 1.20.1
if you can't publish because there's a commit after the bump I can just pop it, the cherry-pick didn't need any interaction

### CODE REVIEW

**Comment by John-Paul-R** [comment]
Thanks for doing this! Changed to target the (new) 1.20.1 branch, as you suggested.

Aside: sorry it took so long to review. I kinda disappeared from most interwebs things for ~a month and a half. Trying to play catch-up today.

**Comment by John-Paul-R** [comment]
Bleh, I somehow misconfigured my `git push` to hit your repo instead of mine (I suspect a `gh` cli feature I didn't fully understand). Inadvertently force-pushed to your branch instead of mine.

This is what _should_ be on this branch: https://github.com/John-Paul-R/Essential-Commands/tree/arno/1.20.1

I'd revert the change to this, but it seems GH has a "conditional permissions" thing, where it'll only let me do so while 1) the PR was open, and 2) there were differences between the source and target branches.

I'll rebase & ff the changes from this PR on the target.

**Comment by arnokeesman** [comment]
Could this get a release on the mod websites as well?

**Comment by John-Paul-R** [comment]
good call, I'd have missed that, tracking in #266, to be done this weekend

**Pull request closed without merging**
