### PR TITLE
Backport #285 to 1.20.1

### PR DESCRIPTION
**Pull request by LittleCircleOO**
The changes in #285 work seamlessly on 1.20.1.
Porting this feature to 1.20.1 based on the fact that 1.20.1 is the version that many modules still support.

### CODE REVIEW

**Comment by John-Paul-R** [comment]
I'll do my best to send out a release for this, along with other recent features soon!

(incidentally, do you know why 1.20.1 is this commonly-supported version? I'm curious, and a bit out of the loop)

**Comment by LittleCircleOO** [comment]
> (incidentally, do you know why 1.20.1 is this commonly-supported version? I'm curious, and a bit out of the loop)

This is related to Mojang's new release strategy since 1.19.3, after which Mojang often added features from the next release as experimental features to the current release, making it more difficult to adapt between minor versions, and some mods (especially those with gameplay changes) chose to stay in the last minor releases that didn't include experimental content, such as 1.19.2 and 1.20.1.

**Comment by John-Paul-R** [comment]
Oh, very interesting. Sounds like a perfectly reasonable reason to wait. Thanks for the explanation!

**Comment by John-Paul-R** [comment]
Released! [0.35.2-mc1.20.1](https://github.com/John-Paul-R/Essential-Commands/releases/tag/0.35.2-mc1.20.1)

**Pull request merged**
